# Generated by Django 5.0 on 2024-06-24 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJblog', '0014_alter_comment_created_at_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='comment_writer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
